[package]
name = "satnogs_api_client"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
serde_urlencoded = "0.7.1"
ureq = { version = "3.1.4", features = ["json"] }
satnogs_libapiclient = {path = "../satnogs_libapiclient"}

[[bin]]
name = "satnogs-api-client"
path = "src/main.rs"

#[lib]
#name = "satnogs_pyclient"
## "cdylib" is necessary to produce a shared library for Python to import from.
#crate-type = ["cdylib"]
#path = "src/lib.rs"
#
#[dependencies.pyo3]
#version = "0.27.2"
## "abi3-py38" tells pyo3 (and maturin) to build using the stable ABI with minimum Python version 3.8
#features = ["abi3-py38",]
## features = ["abi3-py38", "extension-module"]
